name: Android Pull Request Master CI

on:
  pull_request:
    branches:
      - 'master'

  push:
    branches:
      - 'master'

jobs:
  test:
    runs-on: macOS-latest
    strategy:
      matrix:
        api-level: [27, 28, 30]
    steps:
      - name: checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: run tests
        uses: reactivecircus/android-emulator-runner@v1
        with:
          api-level: ${{ matrix.api-level }}
          script: ./gradlew connectedCheck