name: Android Pull Request Master CI

on:
  pull_request:
    branches:
      - 'master'

  push:
    branches:
      - 'master'

jobs:
  Instrumented Test:
    runs-on: macOS-latest
    strategy:
      matrix:
        api-level: [15, 27, 28, 29]
    steps:
      - name: checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: run tests
        uses: reactivecircus/android-emulator-runner@v1
        with:
          api-level: ${{ matrix.api-level }}
          script: ./gradlew connectedCheck

  Unit Test:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
      - name: setup JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Unit tests
        with:
          script: ./gradlew test